FROM node:18.12-buster

WORKDIR /usr/src/app

# Copy package files separately to leverage Docker caching
COPY package.json ./
COPY package-lock.json ./

# Install dependencies
RUN npm install --force

# Copy the rest of the application code
COPY . ./

# Default API base URL
ENV REACT_APP_API_BASE_URL=https://staging-consent-bb-api.igrant.io/v2
ENV REACT_APP_CLIENT_ID=igrant-ios-app
ENV REACT_APP_VERSION=2023.10.4

# Start the application
CMD ["npm", "start"]
